# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
- group: test_variable_group

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    echo using variables in variable group
    echo $(variable1)
  displayName: 'Run a multi-line script'

- task: DownloadSecureFile@1
  inputs:
    secureFile: 'Naveen_Kumar_Dharmapuram_DevOps_Automation_V2.docx'
