trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Build
  displayName: 'Build and Test'
  strategy:
    matrix:
      linux_node12:
        imageName: 'ubuntu-latest'
        node_version: '12.x'
        python_version: '3.x'
      linux_node14:
        imageName: 'ubuntu-latest'
        node_version: '14.x'
        python_version: '3.x'
      windows_node12:
        imageName: 'windows-latest'
        node_version: '12.x'
        python_version: '3.x'
      windows_node14:
        imageName: 'windows-latest'
        node_version: '14.x'
        python_version: '3.x'
  pool:
    vmImage: $(imageName)
  steps:
  - task: UseNode@1
    inputs:
      version: '$(node_version)'
      checkLatest: true
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python_version)'
      addToPath: true
  - script: |
      echo "Node version:"
      node -v
      echo "python verion"
      python -v
    displayName: 'Install dependencies and run tests'
