trigger: none  # Pipeline is not triggered automatically

pr:  # Configuration for pull request triggers
  branches:
    include:
    - master  # Trigger on pull requests targeting the master branch
  paths:
    exclude:
    - 'README.md'  # Exclude README.md file from triggering pull requests

pool:
  vmImage: 'windows-latest'  # Specifies the agent pool and the type of virtual machine to use

jobs:
- job: ManualJob
  displayName: 'Manual Triggered Job'
  steps:
  - task: PowerShell@2
    displayName: 'Run PowerShell Script'
    inputs:
      targetType: 'inline'
      script: |
        Write-Host "Hello, world!"
      errorActionPreference: 'stop'